{
  "headers": {
    "client_id": "s",
    "client_secret": "a",
    "authorization": "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2hpIiwiaWF0IjoxNjI0Nzk0MzQ5LCJleHAiOjE2MjQ4ODA3NDl9.0ReFsfLdJe5faZRKANWEJvz82dya2PELncZ07boydDlBFAQ-YPOMuOxLZAMOXkiPQ7OlKr-xV5Sm7dEIqLilEQ",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "5c8f658b-25ce-40b0-a7b1-30f7935eabbb",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "5"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employee",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employee",
  "listenerPath": "/api/*",
  "relativePath": "/api/employee",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/employee",
  "rawRequestPath": "/api/employee",
  "remoteAddress": "/127.0.0.1:61047",
  "requestPath": "/api/employee"
}